name: Ready the code and deploy
on: [push,workflow_dispatch]
jobs:
  test-code: 
    runs-on: ubuntu-latest
    steps:
      - name: copying the code
        uses: actions/checkout@v4
      
      - name: install nodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.3
     
      - name: check node version
        run: node -v
      
      - name: install dependecies
        run: npm install --frozen-lockfile
      - name: test code
        run: echo "testing code"

  build-code:
    runs-on: ubuntu-latest
    needs: test-code
    steps:
      
      - name: install nodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.3

      - name: copying the code
        uses: actions/checkout@v4
     
      
      - name: install dependecies
        run: npm install --frozen-lockfile

      - name: build the code
        run: npm run build
  
  deploy-code:
    runs-on: ubuntu-latest
    needs: build-code

    steps:
      - name: deploy the code
        run: echo "code deployed"



